language: go
go:
  - 1.x

jobs:
  include:
  - os: linux
    env: RACE="-race"
  - os: linux
    env: GIMME_OS=linux GIMME_ARCH=386
  - os: windows
    env: RACE="-race"

before_install:
  # use local source tree when testing forks
  - mkdir -p $GOPATH/src/github.com/dop251/
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/dop251/ || true

script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then diff -u <(echo -n) <(gofmt -d .); fi
  - go vet ./...
  - go test -short $RACE ./...
