name: Publish type definitions to npm
inputs:
  VERSION:
    description: Packages version
    required: true
  NODE_AUTH_TOKEN:
    description: Node auth token
    required: true
runs:
  using: composite
  steps:
    - name: Set versions
      shell: bash
      run: |
        for pkg in global-types url/types; do
          jq --arg version "{{ inputs.VERSION }}" '.version = $version' $pkg/package.json > $pkg/tmp.json && mv $pkg/tmp.json $pkg/package.json
        done
    - name: Update dependency versions
      shell: bash
      run: |
        for pkg in url/types; do
          jq --arg version "{{ inputs.VERSION }}" '.dependencies."@dop251/types-goja_nodejs-global" = $version' $pkg/package.json > $pkg/tmp.json && mv $pkg/tmp.json $pkg/package.json
        done
    - name: Publish the packages
      shell: bash
      run: |
        cd global-types
        npm publish
        cd ../url/types
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
