name: Publish type definitions to npm
inputs:
  VERSION:
    description: Packages version
    required: true
  NODE_AUTH_TOKEN:
    description: Node auth token
    required: true
runs:
  using: composite
  steps:
    - name: Set variables
      id: vars
      shell: bash
      run: |
        echo "PKGS=buffer url" >> "${GITHUB_OUTPUT}"        

    - name: Set versions
      shell: bash
      run: |
        jq --arg version "${{ inputs.VERSION }}" '.version = $version' global-types/package.json > global-types/tmp.json && mv global-types/tmp.json global-types/package.json
        for pkg in ${{ steps.vars.outputs.PKGS }}; do
          jq --arg version "${{ inputs.VERSION }}" '.version = $version' $pkg/types/package.json > $pkg/types/tmp.json && mv $pkg/types/tmp.json $pkg/types/package.json
        done
    - name: Update dependency versions
      shell: bash
      run: |
        for pkg in ${{ steps.vars.outputs.PKGS }}; do
          jq --arg version "${{ inputs.VERSION }}" '.dependencies."@dop251/types-goja_nodejs-global" = $version' $pkg/types/package.json > $pkg/types/tmp.json && mv $pkg/types/tmp.json $pkg/types/package.json
        done
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'
    - name: Publish the packages
      shell: bash
      run: |
        cd global-types
        npm publish --access=public
        cd -
        for pkg in ${{ steps.vars.outputs.PKGS }}; do
          cd $pkg/types
          npm publish --access=public
          cd -
        done
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
